[[preface]]
= Preface

[[schedule-documentation-about]]

This section provides a brief overview of the Spring Cloud Scheduler SPI reference documentation.
Think of it as a map for the rest of the document. You can read this reference guide in a
linear fashion or you can skip sections if something does not interest you.

== About the documentation
The Spring Cloud Scheduler SPI reference guide is available in {spring-cloud-scheduler-docs}/html[html],
{spring-cloud-scheduler-docs}/pdf/spring-cloud-scheduler-reference.pdf[pdf]
and {spring-cloud-scheduler-docs}/epub/spring-cloud-scheduler-reference.epub[epub] formats. The
latest copy is available at {spring-cloud-scheduler-docs-current}.

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.

[[scheduler-documentation-getting-help]]
== Getting help
Having trouble with Spring Cloud Scheduler? We would like to help!

* Ask a question. We monitor http://stackoverflow.com[stackoverflow.com] for questions
tagged with http://stackoverflow.com/tags/spring-cloud-scheduler[`spring-cloud-scheduler`].
* Report bugs with Spring Cloud scheduler at
https://github.com/spring-cloud/spring-cloud-scheduler/issues.

NOTE: All of Spring Cloud Scheduler is open source, including the documentation. If you find
a problem with the docs or if you just want to improve them, please {github-code}[get
involved].

[[scheduler-documentation-first-steps]]
== First Steps
If you are just getting started with Spring Cloud Scheduler or with 'Spring' in general, we
suggesting reading the <<getting-started.adoc#getting-started>> chapter.

To get started from scratch, read the following sections:

* "`<<getting-started.adoc#getting-started-introducing-spring-cloud-scheduler>>`"
* "`<<getting-started.adoc#getting-started-system-requirements>>`"

To follow the tutorial, read "`<<getting-started.adoc#getting-started-developing-first-scheduler-implementation>>`"
